# Generated by Django 3.2.8 on 2021-11-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scripts',
            new_name='Script',
        ),
    ]
