# Generated by Django 3.2.8 on 2021-11-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_scripts_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
    ]
