# Generated by Django 3.0.8 on 2021-12-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_systemuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='uid',
            field=models.UUIDField(),
        ),
    ]
