# Generated by Django 3.0.8 on 2021-12-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211220_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='uid',
            field=models.UUIDField(unique=True),
        ),
    ]
