# Generated by Django 3.0.8 on 2022-02-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211222_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
