# Generated by Django 3.0.8 on 2022-02-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220225_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
