# Generated by Django 2.2.10 on 2021-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default-dp.png', upload_to='profile_pictures'),
        ),
    ]
