# Generated by Django 2.2.10 on 2021-10-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20211005_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialized_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
