# Generated by Django 2.2.10 on 2021-10-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20211005_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
