# Generated by Django 3.2.9 on 2021-11-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20211016_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birthday',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
